name: Build & Deploy
env:
  IMAGE_TAG_NODE: ghcr.io/tomi204/lunarys-bridge/node
  IMAGE_TAG_RELAYER: ghcr.io/tomi204/lunarys-bridge/relayer

  IMAGE_VERSION: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
  NEXT_PUBLIC_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_relayer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.relayer
          push: true
          tags: ${{env.IMAGE_TAG_RELAYER}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.node
          push: true
          tags: ${{env.IMAGE_TAG_NODE}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max